const languages = {
    ru:{
        locations_title:'Среда',
        locations_desc:'(В каких условиях будет происходить падение объекта)',
        location_btn:'Выбрать среду 👆',
        earth:'Земля',
        mars:'Марс',
        venus:'Венера',
        titan:'Титан',
        water:'Вода',
        salty_water:'Солёная вода',
        shapes_title:'Форма объекта',
        shapes_desc:'(Какая из представленных фигур больше всего соответствует вашему объекту)',
        shape_btn:'Выбрать объект 👆',
        sphere:'Сфера',
        hemisphere:'Полусфера',
        cube:'Куб',
        cylinder:'Цилиндр (1:1)',
        cone:'Конус (60°)',
        drop:'Каплевидное тело',
        disk:'Диск (плоский)',
        hollowhemisphere:'',
        ellipsoid3X4:'Эллипсоид (3:4)',
        semiellipsoid3X4:'Полуэллипсоид (3:4)',
        rectangularplate:'Прямоугольная плита',
        longtube:'Труба',
        weight_label:'Масса объекта',
        size_label:'Диаметр объекта',
        g:'Г',
        kg:'КГ',
        tons:'Т',
        mm:'ММ',
        sm:'СМ',
        m:'М',
        calculate:'Рассчитать',
        maxSpeed:'Максимальная скорость падения: ',
        kmph:'-- км/ч',
        language:'Язык',
        settings:'Настройки',
        closeSettings:'Закрыть',
        js:{
            closeBtn:'Закрыть',
            diameter:'Диаметр',
            baseDiameter:'Диаметр (основания)',
            edgeLength:'Длина ребра',
            bodyThickness:'Диаметр (толщина) тела',
            bodyLength:'Длина',
            baseLength:'Длина (основания)',
            lengthAndWidth:'Размеры (длина, ширина)',
            lengthAndThickness:'Размеры (длина, толщина)',
            kmph:'км/ч',
        },
    },
    ua:{
        locations_title:'Середовище',
        locations_desc:"(В яких умовах буде відбуватись падіння об'єкта)",
        location_btn:'Обрати середовище 👆',
        earth:'Земля',
        mars:'Марс',
        venus:'Венера',
        titan:'Титан',
        water:'Вода',
        salty_water:'Солона вода',
        shapes_title:"Форма  об'єкта",
        shapes_desc:"(Яка з представленних фігур найбільше відповідає вашому об'єкту)",
        shape_btn:"Обрати об'єкт 👆",
        sphere:'Сфера',
        hemisphere:'Півсфера',
        cube:'Куб',
        cylinder:'Циліндр (1:1)',
        cone:'Конус (60°)',
        drop:'Краплеподібне тіло',
        disk:'Диск (плоский)',
        hollowhemisphere:'Півсфера (порожниста)',
        ellipsoid3X4:'Еліпсоїд (3:4)',
        semiellipsoid3X4:'Напівеліпсоїд (3:4)',
        rectangularplate:'Плита прямокутна',
        longtube:'Труба',
        weight_label:"Маса об'єкта",
        size_label:"Діаметр об'єкта",
        g:'Г',
        kg:'КГ',
        tons:'Т',
        mm:'ММ',
        sm:'СМ',
        m:'М',
        calculate:'Розрахувати',
        maxSpeed:'Максимальна швидкість падіння: ',
        kmph:'-- км/год',
        language:'Мова',
        settings:'Налаштування',
        closeSettings:'Закрити',
        js:{
            closeBtn:'Закрити',
            diameter:'Діаметр',
            baseDiameter:'Діаметр (основи)',
            edgeLength:'Довжина ребра',
            bodyThickness:'Діаметр (товщина) тіла',
            bodyLength:'Довжина',
            baseLength:'Довжина (основи)',
            lengthAndWidth:'Розміри (довжина, ширина)',
            lengthAndThickness:'Розміри (довжина, товщина)',
            kmph:'км/год',
        },
    },
    en:{
        locations_title:'Environment',
        locations_desc:"(In what environmental conditions will your object fall)",
        location_btn:'Choose conditions 👆',
        earth:'Earth',
        mars:'Mars',
        venus:'Venus',
        titan:'Titan',
        water:'Water',
        salty_water:'Salty water',
        shapes_title:"Shape of object",
        shapes_desc:"(Which of the presented shapes best matches your subject)",
        shape_btn:"Choose the shape 👆",
        sphere:'Sphere',
        hemisphere:'Hemisphere',
        cube:'Cube',
        cylinder:'Cylinder (1:1)',
        cone:'Cone (60°)',
        drop:'Drop-like body',
        disk:'Disk (flat)',
        hollowhemisphere:'Hemisphere (hollow)',
        ellipsoid3X4:'Ellipsoid (3:4)',
        semiellipsoid3X4:'Semi-Ellipsoid (3:4)',
        rectangularplate:'Rectangular plate',
        longtube:'Tube',
        weight_label:"Weight",
        size_label:"Diameter",
        g:'G',
        kg:'KG',
        tons:'T',
        mm:'MM',
        sm:'SM',
        m:'M',
        calculate:'Calculate',
        maxSpeed:'Maximum fall speed: ',
        kmph:'-- km/h',
        language:'Language',
        settings:'Settings',
        closeSettings:'Close',
        js:{
            closeBtn:'Close',
            diameter:'Diameter',
            baseDiameter:'Diameter (base)',
            edgeLength:'Edge length',
            bodyThickness:'Diameter (thickness)',
            bodyLength:'Length',
            baseLength:'Length (base)',
            lengthAndWidth:'Dimensions (length, width)',
            lengthAndThickness:'Dimensions (length, thickness)',
            kmph:'km/h',
        },
    },

}

